#!/bin/bash

# Setup script for LWS Email Integration
# Quick setup for Mobutu Zemanga website email templates

echo "=========================================="
echo "🚀 Configuration Email LWS"
echo "=========================================="
echo ""

# Check if .env.local already exists
if [ -f .env.local ]; then
    echo "⚠️  Le fichier .env.local existe déjà."
    read -p "Voulez-vous le remplacer? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Installation annulée."
        exit 1
    fi
fi

echo "📦 Installation des dépendances..."
npm install nodemailer @react-email/render
npm install --save-dev @types/nodemailer

echo ""
echo "📝 Configuration des identifiants SMTP..."
echo ""

# Prompt for SMTP credentials
read -p "Entrez votre email LWS (défaut: info@mobutuzemanga.com): " smtp_user
smtp_user=${smtp_user:-info@mobutuzemanga.com}

read -sp "Entrez le mot de passe de votre email: " smtp_password
echo ""

read -p "Entrez l'hôte SMTP (défaut: smtp.lws.fr): " smtp_host
smtp_host=${smtp_host:-smtp.lws.fr}

read -p "Entrez le port SMTP (défaut: 587): " smtp_port
smtp_port=${smtp_port:-587}

# Create .env.local file
cat > .env.local << EOF
# LWS SMTP Configuration
# Generated by setup-email-lws.sh

SMTP_HOST=$smtp_host
SMTP_PORT=$smtp_port
SMTP_USER=$smtp_user
SMTP_PASSWORD=$smtp_password

# Site Configuration
NEXT_PUBLIC_SITE_URL=https://mobutuzemanga.com
CONTACT_EMAIL=info@mobutuzemanga.com
EOF

echo ""
echo "✅ Fichier .env.local créé avec succès!"
echo ""

# Check if route.ts needs to be updated
if grep -q "TEMPORARY PLACEHOLDER" app/api/contact/route.ts; then
    echo "⚠️  L'API route n'est pas encore activée."
    echo ""
    echo "Pour activer l'envoi d'emails:"
    echo "1. Ouvrez: app/api/contact/route.ts"
    echo "2. Décommentez la section 'METHOD 4: Using LWS SMTP'"
    echo "3. Commentez ou supprimez la section 'TEMPORARY PLACEHOLDER'"
    echo ""
    read -p "Voulez-vous ouvrir le fichier maintenant? (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ${EDITOR:-nano} app/api/contact/route.ts
    fi
else
    echo "✅ L'API route semble déjà configurée."
fi

echo ""
echo "=========================================="
echo "✨ Installation terminée!"
echo "=========================================="
echo ""
echo "Prochaines étapes:"
echo "1. Redémarrez le serveur: npm run dev"
echo "2. Testez le formulaire de contact"
echo "3. Vérifiez vos emails"
echo ""
echo "📚 Documentation complète:"
echo "   - components/email/LWS_SETUP.md"
echo "   - components/email/README.md"
echo ""
echo "🔒 Sécurité: Le fichier .env.local est automatiquement ignoré par git"
echo ""

# Check if server is running
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    echo "⚠️  Le serveur est en cours d'exécution sur le port 3000."
    echo "   Redémarrez-le pour appliquer les changements."
fi

echo ""
echo "✅ Configuration terminée avec succès!"
